
zuul:
    routes:
        gsitemanager:
            url: http://gsite-manager:8082
        gsitecustomer:
            url: http://gsite-customer:8081
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            uri: mongodb://gsite-mongodb-mongos:27017
            database: gsite
        cassandra:
            contactPoints: localhost
            protocolVersion: V4
            compression: LZ4
            keyspaceName: gsite
            repositories:
                enabled: false
    thymeleaf:
        cache: true


server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

jhipster:
    gateway:
        rate-limiting:
            enabled: false
        authorized-microservices-endpoints:
            app1: /api
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 8a1d3b6fa9e302c0415b6d650e9911443f953fd3
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: gsite@localhost
        base-url: http://my-server-url-to-change
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: gsite
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false

application:
