hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

zuul:
    host:
        connect-timeout-millis: 5000
        socket-timeout-millis: 10000
    routes:
        gsitemanager:
            url: http://localhost:8082

        gsitecustomer:
            url: http://localhost:8081

spring:
    application:
        name: gsite
    jackson:
        serialization.write_dates_as_timestamps: false
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    mail:
        host: smtp.gmail.com
        port: 587
        username: giftsiteforyou@gmail.com
        password: gsite.system
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    social:
        google:
            clientId: 1013279057915-011ku3rgml86rk9878i1korg82fs5rdi.apps.googleusercontent.com
            clientSecret: zGJd-pCSMIWLNUZV7VevJKld
        facebook:
            clientId: 940460799422307
            clientSecret: ec8a1fb5c9bc3d102748929f6f4dbb53
        twitter:
            clientId: TIUAr6TEk1sFpAKnVsAcOoPjl
            clientSecret: nlRr3spZodHp1u0JfFxwirlcbDcvgesRTINoez07vthk5mnFTQ

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true

storage:
    url:
        image: /

application:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000

    mail:
        from: gsite@localhost
    swagger:
        default-include-pattern: /api/.*
        title: gsite API
        description: gsite API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    social:
            redirectAfterSignIn: "/social-auth"
    ribbon:
        display-on-active-profiles: dev
